const ERROR_CODES = {
  USER: {
    CREATE_FAILED: "USER_CREATE_FAILED",
    NOT_FOUND: "USER_NOT_FOUND",
    UPDATE_FAILED: "USER_UPDATE_FAILED",
    DELETE_FAILED: "USER_DELETE_FAILED",
    DUPLICATE_EMAIL: "USER_DUPLICATE_EMAIL",
  },
  AUTH: {
    LOGIN_FAILED: "AUTH_LOGIN_FAILED",
    UNAUTHORIZED: "AUTH_UNAUTHORIZED",
    FORBIDDEN: "AUTH_FORBIDDEN",
    TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
    TOKEN_INVALID: "AUTH_TOKEN_INVALID",
    PASSWORD_INVALID: "AUTH_PASSWORD_INVALID",
    PASSWORD_MISMATCH: "AUTH_PASSWORD_MISMATCH",
    URL_NOT_FOUND: "AUTH_URL_NOT_FOUND",
    OTP_INVALID: "AUTH_OTP_INVALID",
    PASSWORD_INCORRECT: "AUTH_PASSWORD_INCORRECT",
  },
  SCHOOL: {
    NOT_FOUND: "SCHOOL_NOT_FOUND",
  },
};

export default ERROR_CODES;
